version: '3.1'

services:

  node.portafolio-backend-angular:
    image: node:alpine
    user: 'node'
    working_dir: /home/node/app
    container_name: 'node.portafolio-backend-angular'
    restart: 'always'
    depends_on: 
      - mongo
    environment:
      NODE_ENV: ${NODE_ENV-production}
    volumes:
      - ./:/home/node/app
    ports:
      # Here set you personal port
      - ${NODE_PORT-1000}:${NODE_PORT-1000}
    command: 'npm start'

  mongo:
    image: mongo
    restart: 'always'
    container_name: 'mongo'
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD-example}
    volumes:
    # Windows
      - mongo_database:/data/db
      - mongo_config_database:/data/configdb
      # GNU/Linux
      # - ./database/db:/data/db
      # - ./database/configdb:/data/configdb
volumes:
  mongo_database:
  mongo_config_database: